### ISSUE TITLE
Army account flow

### ISSUE THREAD

**Issue by mdalamin3091** [HypeScout/project-management#26]
## Signup Flow

- [ ] Signup process
- [x] Verify OTP
- [x] OTP verify before login
- [x] Verify OTP  & OTP Success Modal handling
- [x] Resend OTP code Api handle
- [x] When submit OTP code then handle reset OTP form
- [x] Set all error message using status code 
- [x] Check all form validation
- [ ] Error handling with proper message
- [x] Toast modal design with error message
- [ ] Influencer social signup handling 
- [x] handle local storage for brand & influencer individually 
- [x] Forgot password & set new password handle
- [ ]

**Comment by md-abdul-halim-rafi** [comment]
## Signup Flow

- [x] Signup process
- [x] Verify OTP
- [ ] OTP verify before login
- [x] Verify OTP  & OTP Success Modal handling
- [ ] Resend OTP code Api handle
- [x] When submit OTP code then handle reset OTP form
- [ ] Set all error message using status code 
- [ ] Check all form validation
- [ ] Error handling with proper message
- [ ] Toast modal design with error message
- [x] Influencer social signup handling 
- [ ] handle local storage for brand & influencer individually 
- [x] Forgot password & set new password handle
