### ISSUE TITLE
Influencer web account management last time issue track

### ISSUE THREAD

**Issue by md-abdul-halim-rafi** [HypeScout/project-management#44]
- [x] Change city from user settings
- [x] Change password behaviour
- [ ] Forgot password new UI

### @mdalamin3091 
- [x] Country contact code issue first time

### @RHShoumik 
- [x] Phone takhe logout er por 404 astese. Redirection thik moto hoi na 
- [ ] Can't select heic in pc , In mobile I can select heic file but the preview is broken. But can't upload any image 
- [x] Username is taking only numbers.( EX : 1111), It should better like (ex: rh1111)

**Comment by RHShoumik** [comment]
### @rafezhossain9 
- [x] Phone Number Input design problem. 

![Image](https://user-images.githubusercontent.com/44612987/222944066-70f3464c-5c22-4320-8422-36381c8b4bae.png)



- [x] Username first letter must not capital.


![Image](https://user-images.githubusercontent.com/44612987/222945559-191f5f9a-6524-4836-b215-3be4c9d0e2a9.png)

- [ ] Toast message new ta hobe (Influencer web e )


![Image](https://user-images.githubusercontent.com/44612987/222945579-8741654f-98a3-4453-9f28-28690bbcdac4.png)
